#---------------------------------------------------------------------
# GitHub Action Workflow Basics
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Denis Astahov ADV-IT Copyleft (c) 2019
#---------------------------------------------------------------------
name: My-GitHubActions-Basics


on: 
  push:
    branches: 
      - master


jobs:
  my_testing:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Print nice message from Testing Job
        run : echo "Hello World from Test"

      - name: Execute few commands
        run : |
          echo "Hello Message1"
          echo "Hello Message2"
          
      - name: List current folder
        run : ls -la
          
      - name: Git clone my repo
        uses: actions/checkout@v1 
        
      - name: List current folder again
        run : ls -la
      
      


  my_deploy:
    runs-on: [ubuntu-latest]
    needs: [my_testing]      
    env:
      VAR1 : "Job Variable 1"
      VAR2 : "Job Variable 2"
    
    steps:
      - name: Print nice message from Deploy Job
        run : echo "Hello World from Deploy"
      
      - name: List current folder
        run : ls -la

     
