#---------------------------------------------------------------------
# GitHub Action Workflow Basics
#
# Version      Date        Info
# 1.0          2019        Initial Version
#
# Made by Denis Astahov ADV-IT Copyleft (c) 2019
#---------------------------------------------------------------------
name: My-GitHubActions-Basics
env: 
  Aplication_name     : "MyNewGGBApp"
  Deploy_Package_Name : "GGB_version_1.0-${{ github.sha }}"


on: 
  push:
    branches: 
      - master


jobs:
  my_testing:
    runs-on: [ubuntu-latest]
    
    steps:
      - name: Print nice message from Testing Job
        run : echo "Hello World from Test"

      - name: Execute few commands
        run : |
          echo "Hello Message1"
          echo "Hello Message2"
          echo "Printing global env variable ${{ env.Deploy_Package_Name }}"
          
      - name: List current folder
        run : ls -la
          
      - name: Git clone my repo
        uses: actions/checkout@v1 
        
      - name: List current folder again
        run : ls -la
      
      


  my_deploy:
    runs-on: [ubuntu-latest]
    needs: [my_testing]      
    env:
      VAR1 : "Job Variable 1"
      VAR2 : "Job Variable 2"
    
    steps:
      - name: Print nice message from Deploy Job
        run : echo "Hello World from Deploy"
      
      - name: List current folder
        run : ls -l
      
      - name: Printing some info
        run: echo "Printing global env variable ${{ env.Aplication_name }}"
      
      - name: Printing more some info
        run: |
          echo "Var1 =  ${{ env.VAR1 }}"
          echo "Var2 =  ${{ env.VAR2 }}"
      - name: Printing super local env vars
        run: echo "This is local variable $LOCAL_VAR1"
        env:
          LOCAL_VAR1: "Hello. Im local variable"
    

     
